version: '3.9'
services:
  database:
    image: postgres:15
    container_name: socks_db
    environment:
      POSTGRES_DB: socks
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - app-network
    ports:
      - "4000:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: socks_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/socks
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge